In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [173]:
df= pd.read_csv("adults.csv")

In [174]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [175]:
df.shape

(48842, 15)

In [176]:
df["workclass"]=df["workclass"].replace("?","Private")
df["occupation"]=df["occupation"].replace("?","Prof-specialty")
df["native-country"]=df["native-country"].replace("?","United-States")

In [177]:
df.head(50)

age         workclass  fnlwgt     education  educational-num  \
0    25           Private  226802          11th                7   
1    38           Private   89814       HS-grad                9   
2    28         Local-gov  336951    Assoc-acdm               12   
3    44           Private  160323  Some-college               10   
4    18           Private  103497  Some-college               10   
5    34           Private  198693          10th                6   
6    29           Private  227026       HS-grad                9   
7    63  Self-emp-not-inc  104626   Prof-school               15   
8    24           Private  369667  Some-college               10   
9    55           Private  104996       7th-8th                4   
10   65           Private  184454       HS-grad                9   
11   36       Federal-gov  212465     Bachelors               13   
12   26           Private   82091       HS-grad                9   
13   58           Private  299831       HS-grad                9   
14   48           Private  279724       HS-grad                9   
15   43           Private  346189       Masters               14   
16   20         State-gov  444554  Some-college               10   
17   43           Private  128354       HS-grad                9   
18   37           Private   60548       HS-grad                9   
19   40           Private   85019     Doctorate               16   
20   34           Private  107914     Bachelors               13   
21   34           Private  238588  Some-college               10   
22   72           Private  132015       7th-8th                4   
23   25           Private  220931     Bachelors               13   
24   25           Private  205947     Bachelors               13   
25   45  Self-emp-not-inc  432824       HS-grad                9   
26   22           Private  236427       HS-grad                9   
27   23           Private  134446       HS-grad                9   
28   54           Private   99516       HS-grad                9   
29   32  Self-emp-not-inc  109282  Some-college               10   
30   46         State-gov  106444  Some-college               10   
31   56  Self-emp-not-inc  186651          11th                7   
32   24  Self-emp-not-inc  188274     Bachelors               13   
33   23         Local-gov  258120  Some-college               10   
34   26           Private   43311       HS-grad                9   
35   65           Private  191846       HS-grad                9   
36   36         Local-gov  403681     Bachelors               13   
37   22           Private  248446       5th-6th                3   
38   17           Private  269430          10th                6   
39   20           Private  257509       HS-grad                9   
40   65           Private  136384       Masters               14   
41   44      Self-emp-inc  120277     Assoc-voc               11   
42   36           Private  465326       HS-grad                9   
43   29           Private  103634          11th                7   
44   20         State-gov  138371  Some-college               10   
45   28           Private  242832     Assoc-voc               11   
46   39           Private  290208       7th-8th                4   
47   54           Private  186272  Some-college               10   
48   52           Private  201062          11th                7   
49   56      Self-emp-inc  131916       HS-grad                9   

        marital-status         occupation   relationship                race  \
0        Never-married  Machine-op-inspct      Own-child               Black   
1   Married-civ-spouse    Farming-fishing        Husband               White   
2   Married-civ-spouse    Protective-serv        Husband               White   
3   Married-civ-spouse  Machine-op-inspct        Husband               Black   
4        Never-married     Prof-specialty      Own-child               White   
5        Never-married      Other-service  Not-in-famil

In [178]:
# education Category
df.education= df.education.replace(['Preschool', '1st-4th', '5th-6th', '7th-8th', '9th','10th', '11th', '12th'], 'school')
df.education = df.education.replace('HS-grad', 'high school')
df.education = df.education.replace(['Assoc-voc', 'Assoc-acdm', 'Prof-school', 'Some-college'], 'higher')
df.education = df.education.replace('Bachelors', 'undergrad')
df.education = df.education.replace('Masters', 'grad')
df.education = df.education.replace('Doctorate', 'doc')

In [179]:
#martial status
df['marital-status']= df['marital-status'].replace(['Married-civ-spouse', 'Married-AF-spouse'], 'married')
df['marital-status']= df['marital-status'].replace(['Never-married'], 'not-married')
df['marital-status']= df['marital-status'].replace(['Divorced', 'Separated','Widowed',
                                                   'Married-spouse-absent'], 'other')

In [180]:
# income
df.income = df.income.replace('<=50K', 0)
df.income = df.income.replace('>50K', 1)

In [181]:
df.head()

age  workclass  fnlwgt    education  educational-num marital-status  \
0   25    Private  226802       school                7    not-married   
1   38    Private   89814  high school                9        married   
2   28  Local-gov  336951       higher               12        married   
3   44    Private  160323       higher               10        married   
4   18    Private  103497       higher               10    not-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4     Prof-specialty    Own-child  White  Female             0             0   

   hours-per-week native-country  income  
0              40  United-States       0  
1              50  United-States       0  
2              40  United-States       1  
3              40  United-States       1  
4              30  United-States       0

In [182]:
X= df.drop(['income'],axis=1)
y = df['income']

In [183]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
df1= df.copy()
df1= df1.apply(LabelEncoder().fit_transform)
df1.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0    8          3   19329          4                6               1   
1   21          3    4212          2                8               0   
2   11          1   25340          3               11               0   
3   27          3   11201          3                9               0   
4    1          3    5411          3                9               1   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0           6             3     2       1             0             0   
1           4             0     4       1             0             0   
2          10             0     4       1             0             0   
3           6             0     2       1            98             0   
4           9             3     4       0             0             0   

   hours-per-week  native-country  income  
0              39              38       0  
1              49              38       0  
2              39              38       1  
3              39              38       1  
4              29              38       0

In [184]:
X= df1.drop(['income'],axis=1)
y = df1['income']

In [185]:
X

age  workclass  fnlwgt  education  educational-num  marital-status  \
0        8          3   19329          4                6               1   
1       21          3    4212          2                8               0   
2       11          1   25340          3               11               0   
3       27          3   11201          3                9               0   
4        1          3    5411          3                9               1   
...    ...        ...     ...        ...              ...             ...   
48837   10          3   21582          3               11               0   
48838   23          3   10584          2                8               0   
48839   41          3   10316          2                8               2   
48840    5          3   16813          2                8               1   
48841   35          4   23321          2                8               0   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
0               6             3     2       1             0             0   
1               4             0     4       1             0             0   
2              10             0     4       1             0             0   
3               6             0     2       1            98             0   
4               9             3     4       0             0             0   
...           ...           ...   ...     ...           ...           ...   
48837          12             5     4       0             0             0   
48838           6             0     4       1             0             0   
48839           0             4     4       0             0             0   
48840           0             3     4       1             0             0   
48841           3             5     4       0           112             0   

       hours-per-week  native-country  
0                  39              38  
1                  49              38  
2                  39              38  
3                  39              38  
4                  29              38  
...               ...             ...  
48837              37              38  
48838              39              38  
48839              39              38  
48840              19              38  
48841              39              38  

[48842 rows x 14 columns]

In [186]:
y

0        0
1        0
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    0
48841    1
Name: income, Length: 48842, dtype: int64

ss= StandardScaler().fit(df1.drop('income', axis=1))

ss

X= ss.transform(df1.drop('income', axis=1))
y= df['income']

X

In [187]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test, = train_test_split(X, y, test_size=0.3, random_state=0)

In [188]:
print(y_test)

38113    0
39214    1
44248    1
10283    0
26724    0
        ..
48826    1
44230    0
27824    0
13582    0
14557    0
Name: income, Length: 14653, dtype: int64


In [189]:
X_test

age  workclass  fnlwgt  education  educational-num  marital-status  \
38113   19          3    2835          5               12               1   
39214   40          4    1174          3               14               0   
44248   32          3   23308          1               13               2   
10283   37          5   14296          4                2               0   
26724    0          5   19521          4                5               1   
...    ...        ...     ...        ...              ...             ...   
48826   22          1    6303          3               11               0   
44230   30          0   17224          2                8               0   
27824   48          3   17263          2                8               0   
13582   26          5   20798          4                0               0   
14557    7          3   18239          3                9               1   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
38113           9             1     4       1             0             0   
39214           9             0     4       1             0             0   
44248          11             1     4       1            75             0   
10283           4             0     4       1             0             0   
26724           7             3     4       0             0             0   
...           ...           ...   ...     ...           ...           ...   
48826           0             5     4       0             0             0   
44230           9             5     2       0             0             0   
27824           0             0     4       1             0             0   
13582          13             0     2       1             0             0   
14557           9             1     4       1             0             0   

       hours-per-week  native-country  
38113              39              38  
39214              35              38  
44248              44              38  
10283              54              38  
26724              23              38  
...               ...             ...  
48826              19              38  
44230              39              38  
27824              19              38  
13582              39              13  
14557              59              38  

[14653 rows x 14 columns]

In [190]:
y_test

38113    0
39214    1
44248    1
10283    0
26724    0
        ..
48826    1
44230    0
27824    0
13582    0
14557    0
Name: income, Length: 14653, dtype: int64

In [191]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

model1 = rfc.fit(X_train, y_train)
prediction1 = model1.predict(X_test)

print("Acc on training data: {:,.3f}".format(rfc.score(X_train, y_train)))
print("Acc on test data: {:,.3f}".format(rfc.score(X_test, y_test)))

Acc on training data: 1.000
Acc on test data: 0.857


In [192]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [193]:
print(confusion_matrix(y_test, prediction1))

[[10366   772]
 [ 1317  2198]]


In [194]:
print(classification_report(y_test, prediction1))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91     11138
           1       0.74      0.63      0.68      3515

    accuracy                           0.86     14653
   macro avg       0.81      0.78      0.79     14653
weighted avg       0.85      0.86      0.85     14653



In [195]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction1)

0.8574353374735549

In [196]:
df1["gender"].value_counts()

1    32650
0    16192
Name: gender, dtype: int64

In [197]:
df1["gender"].value_counts()[1]

32650

In [198]:
prediction1 = model1.predict(X_test)
prediction1[:25]

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0])

In [199]:
print(prediction1)

[0 1 1 ... 0 0 0]


In [200]:
np.array(y_test)[:25]

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0])

In [201]:
model1.classes_

array([0, 1])

In [202]:
confusion_matrix(y_test, prediction1, labels=(1,0))

array([[ 2198,  1317],
       [  772, 10366]])

In [203]:
print(len(prediction1))

14653


In [204]:
print(len(y_test))

14653


In [205]:
def comp_confmat(y_test, prediction1):

    classes = np.unique(y_test) # extract the different classes
    matrix = np.zeros((len(classes), len(classes))) # initialize the confusion matrix with zeros

    for i in range(len(classes)):
        for j in range(len(classes)):

            matrix[i, j] = np.sum((y_test == classes[i]) & (prediction1 == classes[j]))

    return matrix

comp_confmat(y_test, prediction1)

array([[10366.,   772.],
       [ 1317.,  2198.]])

In [206]:
print(y_test)

38113    0
39214    1
44248    1
10283    0
26724    0
        ..
48826    1
44230    0
27824    0
13582    0
14557    0
Name: income, Length: 14653, dtype: int64


In [207]:
print(prediction1)

[0 1 1 ... 0 0 0]


In [141]:
def calcaccuracy(data,gender,y_test,y_pred,):
    if gender=='1' and y_test==y_pred:
        return 1


In [218]:

cur_gen=1
count=0
y_test=np.array(y_test)
for i in range(len(y_test)) :
    if cur_gen==X_test.loc[X_test.index,'gender'] and y_test[i]==prediction1[i]:
        count+=1
#print(count/X_test['gender'].value_counts()[cur_gen])

TypeError: 'Int64Index' object is not callable

In [149]:
prediction1

array([0, 1, 0, ..., 0, 0, 0])

38113     True
39214     True
44248    False
10283     True
26724     True
         ...  
48826     True
44230    False
27824     True
13582     True
14557     True
Name: income, Length: 14653, dtype: bool

array([0, 1, 1, ..., 0, 0, 0])

array([0, 1, 0, ..., 0, 0, 0])

38113    False
39214     True
44248     True
10283    False
26724     True
         ...  
48826    False
44230     True
27824    False
13582    False
14557    False
Length: 14653, dtype: bool

In [169]:
X_test['gender']

38113    1
39214    1
44248    1
10283    1
26724    0
        ..
48826    0
44230    0
27824    1
13582    1
14557    1
Name: gender, Length: 14653, dtype: int64

In [211]:
(X_test['gender']==X_test.loc[X_test.index,'gender']).count()

14653

In [217]:
X_test.loc[X_test.index,'gender']

38113    1
39214    1
44248    1
10283    1
26724    0
        ..
48826    0
44230    0
27824    1
13582    1
14557    1
Name: gender, Length: 14653, dtype: int64

In [226]:
test_final=pd.DataFrame()

In [227]:
test_final

Empty DataFrame
Columns: []
Index: []

In [228]:
test_final['Gender']=X_test['gender']

In [229]:
test_final['Y_test']=y_test
#y_test[i]==prediction1[i]

In [232]:
test_final['Prediction']=prediction1[i]

In [233]:
test_final

Gender  Y_test  Prediction
38113       1       0           0
39214       1       1           0
44248       1       1           0
10283       1       0           0
26724       0       0           0
...       ...     ...         ...
48826       0       1           0
44230       0       0           0
27824       1       0           0
13582       1       0           0
14557       1       0           0

[14653 rows x 3 columns]

In [ ]:
cur_gen=1
count=0
y_test=np.array(y_test)
for i in range(len(y_test)) :
    if cur_gen==X_test.loc[X_test.index,'gender'] and y_test[i]==prediction1[i]:
        count+=1
#print(count/X_test['gender'].value_counts()[cur_gen])

In [239]:
test_final

Gender  Y_test  Prediction
38113       1       0           0
39214       1       1           0
44248       1       1           0
10283       1       0           0
26724       0       0           0
...       ...     ...         ...
48826       0       1           0
44230       0       0           0
27824       1       0           0
13582       1       0           0
14557       1       0           0

[14653 rows x 3 columns]

In [264]:
cur_gen=1
count=0
for ind in test_final.index:
    if test_final['Gender'][ind]==cur_gen and test_final['Y_test'][ind]==test_final['Prediction'][ind]:
        count+=1
print(count)
a=count
print("For Gender = {} is Correct Accuracy is {}" .format(cur_gen,count/test_final["Gender"].value_counts()[1]))

6780
For Gender = 1 is Correct Accuracy is 0.6963845521774856


In [265]:
cur_gen=1
count=0
for ind in test_final.index:
    if test_final['Gender'][ind]==cur_gen and test_final['Y_test'][ind]!=test_final['Prediction'][ind]:
        count+=1
print(count)
b=count
print("For Gender = {} is InCorrect Accuracy is {}" .format(cur_gen,count/test_final["Gender"].value_counts()[1]))

2956
For Gender = 1 is InCorrect Accuracy is 0.3036154478225144


In [266]:
cur_gen=0
count=0
for ind in test_final.index:
    if test_final['Gender'][ind]==cur_gen and test_final['Y_test'][ind]==test_final['Prediction'][ind]:
        count+=1
print(count)
c=count
print("For Gender = {} is Correct Accuracy is {}" .format(cur_gen,count/test_final["Gender"].value_counts()[1]))

4358
For Gender = 0 is Correct Accuracy is 0.44761709120788823


In [267]:
cur_gen=0
count=0
for ind in test_final.index:
    if test_final['Gender'][ind]==cur_gen and test_final['Y_test'][ind]!=test_final['Prediction'][ind]:
        count+=1
print(count)
d=count
print("For Gender = {} is InCorrect Accuracy is {}" .format(cur_gen,count/test_final["Gender"].value_counts()[1]))

559
For Gender = 0 is InCorrect Accuracy is 0.057415776499589156


In [268]:
print(a+b+c+d)

14653
